# Forecasting

This page will cover common forecasting methods. We'll use the same time series developed in the [Time Series](time_series.html) post.

```{r}
#| include: false

library(data.table)
library(lehighCube)
library(ggplot2)
library(forecast)

orders <- sql_query("select * from order_qty_by_acct_style_and_date where style = 'GB8012'")

gb <- orders[,.(qty = sum(qty), dllrs = sum(dllrs))
         , .(date = lubridate::floor_date(as.Date(date), "months"))
       ][,tidyr::complete(.SD, date = seq.Date(min(date), max(date), "months"), fill = list(qty = 0, dllrs = 0))
        ]
setDT(gb)
gb[,month := month(date)]

gb.ts <- gb[date >= "2021-01-01" & date < "2023-02-01"]$qty |>
  ts(frequency = 12, start = gb[date >= "2021-01-01" & date < "2023-02-01"]$month[1])

gb.ts |>
  autoplot() +
  theme_bw() + 
  scale_y_continuous(labels = scales::comma_format()) +
  labs(x = "Time (in Preiods)", y = "Qty", title = "Sales Qty of GB8012")
```

## Exponential Smoothing

Simple exponential smoothing is described as

$$\begin{align} 
s_t &= \alpha{x_t}+(1-\alpha)s_{t-1} \\
s_t &= s_{t-1}+\alpha(x_t-s_{t-1})
\end{align}$$

- $s_t$ is the smoothed result  at $_t$
- $\alpha$ is the smoothing factor. $0 \le \alpha \le 1$  
- $x$ is the observed value

```{r}
ets(gb.ts, model = "MAM", damped = TRUE) |> forecast(h = 12) |> plot()
```

